version: '3.2'

services:
  ros_indigo:
    privileged: true
    build:
      context: ./kinetic
      dockerfile: Dockerfile
    container_name: indigo_sick
    networks:
      - ros_network
    environment:
      - ROS_MASTER_URI=http://ros_master:11311
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      
    volumes:
      - ./kinetic:/kinetic
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  ros_noetic:
    build:
      context: ./noetic2
      dockerfile: Dockerfile
    container_name: noetic_rosaria
    networks:
      - ros_network
    environment:
      - ROS_MASTER_URI=http://ros_master:11311
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./noetic:/noetic
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    tty: true

  ros2_humble:
    build:
      context: ./humble
      dockerfile: Dockerfile
    container_name: ros2_humble_container
    networks:
      - ros_network
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./humble:/humble
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  ros2_foxy_bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    container_name: foxy_bridge_container
    networks:
      - ros_network
    environment:
      - ROS_MASTER_URI=http://ros_master:11311
      - ROS_DOMAIN_ID=0
      # - DISPLAY=${DISPLAY}
      # - QT_X11_NO_MITSHM=1

    # volumes:
    #   - ./bridge:/bridge  
    tty: true

  ros_master:
    image: ros:noetic-ros-core
    container_name: ros_master
    networks:
      - ros_network
    command: roscore
    tty: true

networks:
  ros_network:
    driver: bridge
