version: '3.2'

services:
  ros_noetic:
    privileged: true
    build:
      context: ./noetic2
      dockerfile: Dockerfile
    container_name: noetic_rosaria
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=${DISPLAY}
    volumes:
      # - ros_ws2_src_vol:/home/ros/ros_ws/src:rw
      # - ./source:/root/.ros_ws2:rw
      # - /noetic2/src:/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ros_indigo:
    privileged: true
    build:
      context: ./kinetic
      dockerfile: Dockerfile
    container_name: indigo_sick
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - ./kinetic:/kinetic
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ros2_humble:
    build:
      context: ./humble
      dockerfile: Dockerfile
    container_name: ros2_humble_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./humble:/humble
      - ./humble/source:/humble_ws
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/bus/usb:/dev/bus/usb:rw
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ros2_foxy_bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    container_name: foxy_bridge_container
    environment:
      - DISPLAY=${DISPLAY}
      # - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ./bridge:/ros_bridge
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null
