version: '3.2'

services:
  ros_noetic:
    privileged: true
    build:
      context: ./noetic2
      dockerfile: Dockerfile
    container_name: noetic_rosaria
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=${DISPLAY}
    volumes:
      # - ./Indigo_Sick/source2:/ros_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: roscore

  ros_indigo:
    privileged: true
    build:
      context: ./Indigo_Sick
      dockerfile: Dockerfile
    container_name: indigo_sick
    environment:
      - ROS_MASTER_URI=http://localhost:11311
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ros2_humble:
    build:
      context: ./humble
      dockerfile: Dockerfile
    container_name: ros2_humble_container
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./humble/source2:/home/ros/humble_ws/src
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  ros2_foxy_bridge:
    build:
      context: ./bridge
      dockerfile: Dockerfile
    container_name: foxy_bridge_container
    environment:
      - DISPLAY=${DISPLAY}
      # - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://localhost:11311
    volumes:
      - ./bridge/source:/ros_bridge
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    # command: ros2 run ros1_bridge dynamic_bridge
    